Extend all the scripts with information

diff --git a/.config/scripts/i3battery b/.config/scripts/i3battery
--- a/.config/scripts/i3battery
+++ b/.config/scripts/i3battery
@@ -1,43 +1,62 @@
 #!/usr/bin/env bash
+#===============================================================================
+#
+#          FILE: i3battery
+#
+#         USAGE: ./i3battery
+#
+#   DESCRIPTION: Used by i3blocks to print the battery status.
+#
+#        AUTHOR: tung beier
+#       CREATED: 21 August 2019 19:29 CEST
+#===============================================================================
 
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-# Expect battery number as first parameter.
-# Return current capacity and status.
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-function get_battery_status {
-    local CAPACITY=`cat /sys/class/power_supply/BAT${1}/capacity`
-    local STATUS=`cat /sys/class/power_supply/BAT${1}/status`
+set -o errexit  # Exit when a command fails
+                # Use || true if a command is allowed to fail
+set -o nounset  # Treat unset variables as an error
+set -o pipefail # Exit when a command in a pipeline fails
 
-    if [ "${STATUS}" = "Charging" ]; then
-        color="teal"
-    elif [ "${CAPACITY}" -ge 70 ]; then
-        color="green"
-    elif [ "${CAPACITY}" -ge 35 ]; then
-        color="yellow"
-    else
-        color="red"
-    fi
 
-    case ${STATUS} in
-        Discharging) STATUS=🔋 ;;
-        Charging) STATUS=🔌 ;;
-        Unknown) STATUS=❓ ;;
-        Full) STATUS=⚡ ;;
-    esac
+#---  FUNCTION  ----------------------------------------------------------------
+#          NAME: _get_battery_status
+#   DESCRIPTION: Print the battery information based on it capacity and status
+#    PARAMETERS: $1 = Battery number (either 0 or 1)
+#       RETURNS: The battery information with its color and capacity in prozent
+#-------------------------------------------------------------------------------
+_get_battery_status() {
+  local capacity=$(cat /sys/class/power_supply/BAT${1}/capacity)
+  local status=$(cat /sys/class/power_supply/BAT${1}/status)
 
-    case ${1} in
-        0) TAG=Int ;;
-        1) TAG=Ext ;;
-    esac
+  local color="green"
+  if [[ "$status" = "Charging" ]]; then
+    color="teal"
+  elif [[ "$capacity" -ge 65 ]]; then
+    color="green"
+  elif [[ "$capacity" -ge 25 ]]; then
+    color="yellow"
+  else
+    color="red"
+  fi
 
-#    echo "<span bgcolor='${color}' fgcolor='black'>${TAG} ${CAPACITY}%${STATUS}</span>"
-    echo "<span fgcolor='${color}'>${TAG}${STATUS}${CAPACITY}%</span>"
+  case $status in
+    Discharging) status=🔋 ;;
+    Charging) status=🔌 ;;
+    Unknown) status=❓ ;;
+    Full) status=⚡ ;;
+  esac
+
+  local tag="Unknown"
+  case $1 in
+    0) tag="Int" ;;
+    1) tag="Ext" ;;
+  esac
+
+echo "<span fgcolor='${color}'>${tag}${status}${capacity}%</span>"
 }
 
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-# Script's logic
-#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-BAT0=$(get_battery_status 0)
-BAT1=$(get_battery_status 1)
-echo "${BAT0} <span fgcolor='gray'>|</span> ${BAT1}"
+#---  SCRIPT LOGIC  ------------------------------------------------------------
+bat_0=$(_get_battery_status 0)
+bat_1=$(_get_battery_status 1)
+
+echo "${bat_0} <span fgcolor='gray'>|</span> ${bat_1}"
 
diff --git a/.config/scripts/i3datetime b/.config/scripts/i3datetime
--- a/.config/scripts/i3datetime
+++ b/.config/scripts/i3datetime
@@ -1,6 +1,25 @@
 #!/usr/bin/env bash
+#===============================================================================
+#
+#          FILE: i3datetime
+#
+#         USAGE: ./i3datetime
+#
+#   DESCRIPTION: Used by i3blocks to print the date and time information.
+#
+#        AUTHOR: tung beier
+#       CREATED: 21 August 2019 19:57 CEST
+#===============================================================================
 
-DATE=$(date '+%a - %d %b %Y ')
-TIME=$(date '+%H:%M')
+set -o errexit  # Exit when a command fails
+                # Use || true if a command is allowed to fail
+set -o nounset  # Treat unset variables as an error
+set -o pipefail # Exit when a command in a pipeline fails
 
-echo "<span fgcolor='grey'>${TIME} 🕓 ${DATE}</span>"
+
+#---  SCRIPT LOGIC  ------------------------------------------------------------
+date=$(date '+%a - %d %b %Y ')
+time=$(date '+%H:%M')
+
+echo "<span fgcolor='grey'>${time} 🕓 ${date}</span>"
+
diff --git a/.config/scripts/i3network b/.config/scripts/i3network
--- a/.config/scripts/i3network
+++ b/.config/scripts/i3network
@@ -1,35 +1,61 @@
 #!/usr/bin/env bash
+#===============================================================================
+#
+#          FILE: i3network
+#
+#         USAGE: ./i3network
+#
+#   DESCRIPTION: Used by i3blocks to print the network information.
+#
+#        AUTHOR: tung beier
+#       CREATED: 21 August 2019 20:00 CEST
+#===============================================================================
 
-#     📡
-ETHERNET=enp0s31f6
-WIRELESS=wlp3s0
+set -o errexit  # Exit when a command fails
+                # Use || true if a command is allowed to fail
+set -o nounset  # Treat unset variables as an error
+set -o pipefail # Exit when a command in a pipeline fails
 
-function get_network {
-    local STATE=`cat /sys/class/net/${1}/operstate`
 
-    case ${1} in
-        ${ETHERNET}) TAG= ;;
-        ${WIRELESS}) TAG= ;;
-    esac
+#---  GLOBAL VARIABLES  --------------------------------------------------------
+readonly ethernet_interface=enp0s31f6
+readonly wireless_interface=wlp3s0
 
-    case ${STATE} in
-        up) COLOR="green" ;;
-        down) COLOR="red" ;;
-    esac
 
-    local QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70 - 1) }')
-    if [[ $QUALITY -ge 80 ]]; then
-        echo "#00FF00"
-    elif [[ $QUALITY -lt 40 ]]; then
-        echo "#FF0000"
-    elif [[ $QUALITY -lt 60 ]]; then
-        echo "#FF8000"
-    elif [[ $QUALITY -lt 80 ]]; then
-        echo "#FFF600"
-    fi
+#---  FUNCTION  ----------------------------------------------------------------
+#          NAME: _get_network
+#   DESCRIPTION: Print the current ethernet and wireless network status
+#    PARAMETERS: $1 = the network interface name
+#       RETURNS: The network information
+#-------------------------------------------------------------------------------
+_get_network() {
+  local state=$(cat /sys/class/net/${1}/operstate)
 
-    echo "<span fgcolor='${COLOR}'>${TAG}</span>"
+  local tag=" "
+  if [[ "$1" = "$wireless_interface" ]]; then
+    tag=" "
+  fi
+
+  local color="red"
+  if [[ "$state" = "up" ]]; then
+    color="green"
+  fi
+
+  local quality=$(grep "$wireless_interface" /proc/net/wireless \
+    | awk '{ print int($3 * 100 / 70 - 1) }')
+  if [[ $quality -ge 80 ]]; then
+    echo "#00FF00"
+  elif [[ $quality -lt 40 ]]; then
+    echo "#FF0000"
+  elif [[ $quality -lt 60 ]]; then
+    echo "#FF8000"
+  elif [[ $quality -lt 80 ]]; then
+    echo "#FFF600"
+  fi
+
+  echo "<span fgcolor='${color}'>${tag}</span>"
 }
 
 
-echo "$(get_network ${ETHERNET}) $(get_network ${WIRELESS})"
+#---  SCRIPT LOGIC  ------------------------------------------------------------
+echo "$(_get_network ${ethernet_interface}) $(_get_network ${wireless_interface})"
diff --git a/.config/scripts/i3volume b/.config/scripts/i3volume
--- a/.config/scripts/i3volume
+++ b/.config/scripts/i3volume
@@ -1,21 +1,39 @@
 #!/usr/bin/env bash
+#===============================================================================
+#
+#          FILE: i3volume
+#
+#         USAGE: ./i3volume
+#
+#   DESCRIPTION: Used by i3blocks to display the current sound level.
+#
+#        AUTHOR: tung beier
+#       CREATED: 21 August 2019 20:17 CEST
+#===============================================================================
 
-NEW_VOLUME="pkill -RTMIN+10 i3blocks"
+set -o errexit  # Exit when a command fails
+                # Use || true if a command is allowed to fail
+set -o nounset  # Treat unset variables as an error
+set -o pipefail # Exit when a command in a pipeline fails
+
+
+#---  SCRIPT LOGIC  ------------------------------------------------------------
+new_volume="pkill -RTMIN+10 i3blocks"
 case $1 in
-    up) amixer -q set Master 10%+ ; $NEW_VOLUME ;;
-    down) amixer -q set Master 10%- ; $NEW_VOLUME ;;
+  up) amixer -q set Master 10%+ ; $new_volume ;;
+  down) amixer -q set Master 10%- ; $new_volume ;;
 esac
 
-VOLUME=`amixer get Master | grep % | awk '{print $4}' | sed 's/[^0-9]//g'`
-if [ "${VOLUME}" -eq "0" ]; then
-    ICON=🔇
-elif [ "${VOLUME}" -gt "70" ]; then
-    ICON="🔊"
-elif [ "${VOLUME}" -lt "35" ]; then
-    ICON="🔈"
+volume=$(amixer get Master | grep % | awk '{print $4}' | sed 's/[^0-9]//g')
+if [[ "$volume" -eq "0" ]]; then
+  icon="🔇"
+elif [[ "$volume" -gt "70" ]]; then
+  icon="🔊"
+elif [[ "$volume" -lt "35" ]]; then
+  icon="🔈"
 else
-    ICON="🔉"
+  icon="🔉"
 fi
 
-echo "<span color='white'>${ICON} ${VOLUME}%</span>"
+echo "<span color='white'>${icon} ${volume}%</span>"
 
diff --git a/.config/scripts/wlan b/.config/scripts/wlan
--- a/.config/scripts/wlan
+++ b/.config/scripts/wlan
@@ -1,17 +1,34 @@
 #!/usr/bin/env bash
+#===============================================================================
+#
+#          FILE: wlan
+#
+#         USAGE: ./wlan
+#
+#   DESCRIPTION: Start the wireless interface.
+#
+#       OPTIONS: $1 = wireless configuration to use; default = daynoir24
+#        AUTHOR: tung beier
+#       CREATED: 21 August 2019 20:47 CEST
+#===============================================================================
 
-# Start wlan interface
+set -o errexit  # Exit when a command fails
+                # Use || true if a command is allowed to fail
+set -o nounset  # Treat unset variables as an error
+set -o pipefail # Exit when a command in a pipeline fails
 
-WLAN_INTERFACE=wlp3s0
-WPA_NAME=daynoir24
 
-if [ ! -z "${1}" ]; then
-    WPA_NAME=${1}
+#---  SCRIPT LOGIC  ------------------------------------------------------------
+wireless_interface=wlp3s0
+wpa_name=daynoir24
+
+if [[ ! -z "$1" ]]; then
+  wpa_name=${1}
 fi
 
-echo "Stop ${WLAN_INTERFACE}"
-sudo -S ip link set ${WLAN_INTERFACE} down
+echo "Stop ${wireless_interface}"
+sudo -S ip link set $wireless_interface down
 
-echo "Start ${WPA_NAME}"
-sudo -S netctl start ${WPA_NAME}
+echo "Start ${wpa_name}"
+sudo -S netctl start $wpa_name
 
